AcademicAdvisor/advising_project/advising_app/urls.py
from django.conf import settings
from django.urls import path
from . import views
from .views import edit_current_courses, get_majors_for_school, student_dashboard_view, tutor_students_list
from django.urls import path

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'), 
    path('student/dashboard/', views.student_dashboard_view, name='student_dashboard_view'),
    path('tutor/dashboard/', views.tutor_dashboard_view, name='tutor_dashboard_view'),
    path('logout/', views.user_logout, name='user_logout'),
    path('programs/', views.programs_view, name='programs'),
    path('programs/<int:school_id>/majors/', views.majors_view, name='majors'),
    path('majors/<int:major_id>/details/', views.major_detail, name='major_detail'),
    path('course/<int:course_id>/', views.course_detail, name='course_detail'),
    path('search/', views.search, name='search'),
    path('tutor/students/', tutor_students_list, name='tutor_students_list'),
    path('course/edit/<int:course_id>/', views.edit_current_courses, name='edit_course'),
    path('tutor/update_profile/', views.update_tutor_profile, name='update_tutor_profile'),
    path('student/completed_courses/', views.completed_courses, name='completed_courses'),
    path('student/add_completed_course/', views.add_completed_course, name='add_completed_course'),
    path('student/edit_completed_course/<int:pk>/', views.edit_completed_course, name='edit_completed_course'),
    path('student/remove_completed_course/<int:pk>/', views.remove_completed_course, name='remove_completed_course'),
    path('autocomplete/', views.autocomplete, name='autocomplete'),
    path('student/remaining_courses/', views.calculate_remaining_courses, name='calculate_remaining_courses'),
    path('student/update_profile/', views.update_student_profile, name='update_student_profile'),
    path('student/complete_course/<int:course_id>/', views.complete_course, name='complete_course'),
    path('study-plan/', views.study_plan_view, name='study_plan'), 
    path('student/dashboard/', student_dashboard_view, name='student_dashboard_view'),  
    path('student/dashboard/<int:year>/<str:semester>/', student_dashboard_view, name='student_dashboard_view_with_params'),
    path('tutor/dashboard/', views.tutor_dashboard, name='tutor_dashboard'),
    path('majors/<int:school_id>/', views.majors_view, name='majors'),
    path('major/<int:major_id>/', views.major_detail, name='major_detail'),
    path('tutor/students/', views.tutor_students_list, name='tutor_students_list'),
    path('student/dashboard/', student_dashboard_view, name='student_dashboard'),
    path('student/edit_current_courses/', edit_current_courses, name='edit_current_courses'),
    path('student/dashboard/<int:year>/<str:semester>/', views.student_dashboard_view, name='student_dashboard_view'),
    path('student/<int:student_id>/dashboard/', views.student_dashboard, name='student_dashboard'),
    path('ajax/get_majors_for_school/', get_majors_for_school, name='ajax_get_majors_for_school'),
    path('inbox/', views.inbox, name='inbox'),
    path('send_message/', views.send_message, name='send_message'),
    path('send_message/<int:recipient_id>/', views.send_message, name='send_message_to_student'),
    path('get-completed-courses-data/', views.get_completed_courses_data, name='get_completed_courses_data'),
    path('student_dashboard/<int:student_id>/', views.tutor_student_dashboard_view, name='tutor_student_dashboard_view'),
    path('unread_messages_count/', views.get_unread_messages_count, name='get_unread_messages_count'),
    path('tutor_completed_courses/<int:student_id>/', views.tutor_view_completed_courses, name='tutor_view_completed_courses'),
    path('tutor/remaining_courses/<int:student_id>/', views.tutor_view_remaining_courses, name='tutor_view_remaining_courses'),
    path('study_plan/', views.study_plan_view, name='study_plan_view'),
    path('view_study_plan/', views.view_study_plan, name='view_study_plan'),
    path('view_study_plan/<int:student_id>/', views.view_study_plan, name='view_study_plan'),
    path('tutor_view_study_plan/<int:student_id>/', views.tutor_view_study_plan, name='tutor_view_study_plan'),
    path('delete_current_course/<int:course_id>/', views.delete_current_course, name='delete_current_course'),
    path('tutor/profile/<int:tutor_id>/', views.tutor_profile_view, name='tutor_profile_view'),

]

AcademicAdvisor/advising_project/advising_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='login/', permanent=False)),
    path('', include('advising_app.urls')),
    path('', include('appointment_booking.urls', namespace='appointment_booking')),  
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AcademicAdvisor/advising_project/advising_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.conf import settings
from django.db import models

class School(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Course(models.Model):
    SEMESTER_CHOICES = [
        ("semesterA", "semester A"),
        ("semesterB", "semester B"),
    ]
    COURSE_TYPE_CHOICES = [
        ('elective', 'Elective Course'),
        ('national_requirement', 'National Requirement'),
        ('english', 'English Course'),
        ('compulsory', 'Compulsory Course'),         
        ('major_specific', 'Major Specific Course')  
    ]

    name = models.CharField(max_length=100)
    year = models.PositiveIntegerField(null=True, blank=True)
    semester = models.CharField(max_length=10, choices=SEMESTER_CHOICES, null=True)
    course_credits = models.IntegerField(null=True)
    course_code = models.CharField(max_length=20, null=True)
    course_description = models.TextField(null=True)
    nqf_lvl = models.IntegerField(null=True)
    prerequisites = models.ManyToManyField("self", symmetrical=False, blank=True, related_name='postrequisites')
    course_type = models.CharField(max_length=20, choices=COURSE_TYPE_CHOICES, null=True, blank=True, default='major')

    def __str__(self):
        return self.name

class Major(models.Model):
    name = models.CharField(max_length=100)
    major_credit = models.IntegerField(null=True)
    major_code = models.CharField(max_length=20, null=True)
    description = models.TextField(null=True)
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    courses = models.ManyToManyField(Course)

    def __str__(self):
        return self.name
      

class Meeting(models.Model):
    meeting_date = models.DateField()
    student = models.ForeignKey('CustomUser', on_delete=models.CASCADE, related_name='student_meetings')
    tutor = models.ForeignKey('CustomUser', on_delete=models.CASCADE, related_name='tutor_meetings')
    start_time = models.TimeField(null=True)
    end_time = models.TimeField(null=True)
    status = models.CharField(max_length=10, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending')
    notes = models.TextField(blank=True, null=True)  # Optional field for any notes about the meeting
    
    def __str__(self):
        return f"Meeting on {self.meeting_date}"

from django.utils import timezone

class Message(models.Model):
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='sent_messages', on_delete=models.CASCADE)
    recipient = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='received_messages', on_delete=models.CASCADE)
    subject = models.CharField(max_length=255)
    body = models.TextField()
    sent_at = models.DateTimeField(auto_now_add=True)
    read_at = models.DateTimeField(null=True, blank=True)
    file = models.FileField(upload_to='message_files/', null=True, blank=True)  
    
    def __str__(self):
        return f"Message from {self.sender} to {self.recipient}: {self.subject}"
    
    def mark_as_read(self):
        if self.read_at is None:
            self.read_at = timezone.now()
            self.save()

class TutorProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='tutor_profile')
    location = models.CharField(max_length=255, blank=True, null=True)
    contact_email = models.EmailField(max_length=255)
    working_hours = models.CharField(max_length=255, blank=True, null=True) #removwe this
    start_time = models.TimeField(null=True, blank=True)
    end_time = models.TimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.user.get_full_name()}'s Profile"

class StudentProfile(models.Model):
    user = models.OneToOneField('CustomUser', on_delete=models.CASCADE)
    program = models.CharField(max_length=100, null=True)
    study_year = models.PositiveIntegerField(null=True)
    selected_semester = models.CharField(max_length=20, default='semesterA')
    school = models.ForeignKey(School, on_delete=models.SET_NULL, null=True, blank=True)
    major = models.ForeignKey(Major, on_delete=models.SET_NULL, null=True, blank=True)
    is_scholarship_student = models.BooleanField(default=False, verbose_name="Scholarship Student")

    def __str__(self):
        return f"Profile of {self.user}"

class StudentCourseHistory(models.Model):
    student = models.ForeignKey('CustomUser', on_delete=models.CASCADE)
    course = models.ForeignKey('Course', on_delete=models.CASCADE)  
    year = models.PositiveIntegerField()
    grade = models.CharField(max_length=2)
    custom_semester = models.CharField(max_length=20)
    self_reported = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.student} - {self.course} - {self.grade}"

#StudentProfile model to define the relationship with StudentCourseHistory
StudentProfile.courses_taken = models.ManyToManyField(Course, through=StudentCourseHistory)

class CurrentCourse(models.Model):
    student = models.ForeignKey('CustomUser', on_delete=models.CASCADE, related_name='current_courses')
    course = models.ForeignKey('Course', on_delete=models.CASCADE)
    year = models.PositiveIntegerField()
    semester = models.CharField(max_length=20)  

    def __str__(self):
        return f"{self.student} - {self.course}"
StudentProfile.courses_taken = models.ManyToManyField(Course, through=CurrentCourse)
    

class TutorAssignment(models.Model):
    student = models.ForeignKey('CustomUser', on_delete=models.CASCADE, related_name='assigned_students')
    tutor = models.ForeignKey('CustomUser', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.tutor} assigned to {self.student}"

class StudyPlan(models.Model):
    user = models.ForeignKey('CustomUser', on_delete=models.CASCADE, related_name='study_plans')
    year = models.PositiveIntegerField()  # Add this if 'year' is a property of StudyPlan

    def __str__(self):
        return f"{self.user.get_full_name()}'s Study Plan for {self.year}"  # Updated to include year


class StudyPlanEntry(models.Model):
    study_plan = models.ForeignKey(StudyPlan, on_delete=models.CASCADE, related_name='courses')
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    year_taken = models.PositiveIntegerField()
    semester = models.CharField(max_length=10, choices=Course.SEMESTER_CHOICES)
    grade = models.CharField(max_length=2, blank=True, null=True)

    def __str__(self):
        return f"{self.course.name} - Year {self.year_taken} {self.semester}"


class CustomUser(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_tutor = models.BooleanField(default=False)
    is_manager = models.BooleanField(default=False) #deelete this
    is_admin = models.BooleanField(default=False)

    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

    tutor = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='students')
    groups = models.ManyToManyField(Group, related_name='customuser_set', blank=True)
    user_permissions = models.ManyToManyField(Permission, related_name='customuser_set', blank=True)

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    def get_assigned_tutor(self):
        if hasattr(self, 'tutor'):
          return self.tutor
        return None
    
    def is_student_assigned(self, student_id):
        # This method checks if a student is assigned to the current tutor user
        return self.students.filter(id=student_id).exists()

    def __str__(self):
        return self.email

AcademicAdvisor/advising_project/advising_app/templates/student_templates/add_completed_courses.html
{% extends 'base.html' %}
{% block title %}Add Completed Course{% endblock %}


{% block content %}



<body>

    <div class="container mt-4">
        <h1 class="mb-4">Add Completed Course</h1>
        <form method="post" class="needs-validation" novalidate>
            {% csrf_token %}
            <div class="form-group mb-3">
                <label for="id_course" class="form-label">Course:</label>
                {{ form.course }}
            </div>
            <div class="form-group mb-3">
                <label for="id_year" class="form-label">Year:</label>
                {{ form.year }}
            </div>
            <div class="form-group mb-3">
                <label for="id_grade" class="form-label">Grade:</label>
                {{ form.grade }}
            </div>
            <div class="form-group mb-3">
                <label for="id_custom_semester" class="form-label">Semester:</label>
                {{ form.custom_semester }}
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Save</button>
                <a href="{% url 'completed_courses' %}" class="btn btn-secondary">Back to Completed Courses</a>
            </div>
        </form>
    </div>

</body>
{% endblock %}

AcademicAdvisor/advising_project/advising_app/templates/student_templates/completed_courses.html
{% extends 'base.html' %}
{% block title %}Completed Courses{% endblock %}


{% block content %}


<body>

    <div class="container mt-4">
        {% if not is_tutor_viewing %}
        <h1>My Completed Courses</h1>
        <div class="mb-3">
            <a href="{% url 'add_completed_course' %}" class="btn btn-primary">Add Course</a>
        </div>
        {% else %}
        <h1>{{ student.get_full_name }}'s Completed Courses</h1>
        {% endif %}
        {% if not is_tutor_viewing %}
        
        {% endif %}
        {% if completed_courses %}
        <div class="table-responsive">
            <table class="table table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Course</th>
                        <th scope="col">Year</th>
                        <th scope="col">Semester</th>
                        <th scope="col">Grade</th>
                        {% if not is_tutor_viewing %}
                        <th scope="col">Actions</th>
                        {% endif %}

                    </tr>
                </thead>
                <tbody>
                    {% for course in completed_courses %}
                    <tr>
                        <td>{{ course.course.name }}</td>
                        <td>{{ course.year }}</td>
                        <td>{{ course.custom_semester }}</td>
                        <td>
                            {{ course.grade }}
                            {% if course.grade == 'F' %}
                            <div class="text-danger">You need to retake this course</div>
                            {% endif %}
                        </td>

                        <td>
                            {% if not is_tutor_viewing %}
                            <a href="{% url 'edit_completed_course' course.pk %}" class="btn btn-secondary btn-sm">Edit</a>
                            <form action="{% url 'remove_completed_course' course.id %}" method="post" style="display: inline-block;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Remove</button>
                            </form>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <p>No completed courses added yet.</p>
        {% endif %}
{% if is_tutor %}
<a href="{% url 'tutor_dashboard_view' %}" class="btn btn-outline-secondary back-to-dashboard-btn">Return to Tutor
    Dashboard</a>
{% else %}
<a href="{% url 'student_dashboard_view' %}" class="btn btn-outline-secondary back-to-dashboard-btn">Return to Student
    Dashboard</a>
{% endif %}    </div>

</body>
{% endblock %}

AcademicAdvisor/advising_project/advising_app/templates/student_templates/edit_completed_courses.html
{% extends 'base.html' %}
{% block title %}Completed Courses{% endblock %}


{% block content %}


<body>
    <div class="container mt-4">
        <h1 class="mb-4">Edit Completed Course</h1>
        <form method="post" class="needs-validation" novalidate>
            {% csrf_token %}
            <div class="form-group mb-3"> 
                <label for="id_course">Course:</label>
                {{ form.course }}
            </div>
            <div class="form-group mb-3"> 
                <label for="id_grade">Grade:</label>
                {{ form.grade }}
            </div>
            <div class="form-group mb-3"> 
                <label for="id_year">Year:</label>
                {{ form.year }}
            </div>
            <div class="form-group mb-3"> 
                <label for="id_custom_semester">Semester:</label>
                {{ form.custom_semester }}
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Save Changes</button>
                <a href="{% url 'completed_courses' %}" class="btn btn-secondary">Back to Completed Courses</a>
            </div>
        </form>
    </div>
</body>
{% endblock %}

AcademicAdvisor/advising_project/advising_app/templates/student_templates/edit_current_courses.html
{% extends 'base.html' %}
{% block title %}Edit Current Courses{% endblock %}

<!DOCTYPE html>
<html lang="en">
{% block content %}

<head>
    <meta charset="UTF-8">
    <title>Edit Current Courses</title>
    {% load static %}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/select2/dist/css/select2.min.css" rel="stylesheet" />
</head>

<body>
    <div class="container mt-4">
        <div class="card">
            <div class="card-header bg-primary text-white">
                <h1>Edit Current Courses</h1>
            </div>
            <div class="card-body">
                <form method="post" action="{% url 'edit_current_courses' %}">
                    {% csrf_token %}
                    {% if form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ form.non_field_errors }}
                    </div>
                    {% endif %}

                    {% for field in form %}
                    <div class="mb-3">
                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                        {{ field.as_widget }}
                        {% if field.errors %}
                        <div class="alert alert-danger">{{ field.errors.as_text }}</div>
                        {% endif %}
                    </div>
                    {% endfor %}

                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <input type="submit" value="Save changes" class="btn btn-outline-info " />
                        <a href="{% url 'student_dashboard_view' %}" class="btn btn-secondary">Back to Dashboard</a>
                    </div>
                </form>

                <!-- Current Courses Table -->
                <div class="mt-4">
                    <h2>Current Courses</h2>
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Code</th>
                                <th scope="col">Name</th>
                                <th scope="col">Credits</th>
                                <th scope="col">Semester</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for course in current_courses %}
                            <tr>
                                <td>{{ course.course.course_code }}</td>
                                <td>{{ course.course.name }}</td>
                                <td>{{ course.course.course_credits }}</td>
                                <td>{{ course.semester }}</td>
                                <td>
                                    <a href="{% url 'delete_current_course' course.id %}"
                                        class="btn btn-danger">Delete</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#id_required_courses, #id_elective_courses').select2({
                placeholder: "Select courses",
                allowClear: true
            });
        });
    </script>
</body>
{% endblock %}

</html>

AcademicAdvisor/advising_project/advising_app/templates/student_templates/remaining_courses.html
{% extends 'base.html' %}
{% block title %}Remaining Courses{% endblock %}


{% block content %}

<body>
    <div class="container my-5">
        <div class="text-center mb-4">
            <h1>Remaining Courses for {{ major.name }}</h1>
        </div>

        {% if remaining_courses %}
        <div class="card mb-4">
            <ul class="list-group list-group-flush">
                {% for course in remaining_courses %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <a href="{% url 'course_detail' course.id %}">
                        {{ course.name }} ({{ course.course_code }})
                    </a>
                    <span class="badge bg-primary rounded-pill">{{ course.course_credits }}</span>
                </li>
                {% endfor %}
            </ul>
        </div>
        {% else %}
        <div class="alert alert-success text-center" role="alert">
            Congratulations! You have completed all the required courses for your major.
        </div>
        {% endif %}

        <div class="text-center">
{% if is_tutor %}
<a href="{% url 'tutor_dashboard_view' %}" class="btn btn-outline-secondary back-to-dashboard-btn">Return to Tutor
    Dashboard</a>
{% else %}
<a href="{% url 'student_dashboard_view' %}" class="btn btn-outline-secondary back-to-dashboard-btn">Return to Student
    Dashboard</a>
{% endif %}        
    </div>
        </div>
</body>
{% endblock %}

AcademicAdvisor/advising_project/advising_app/templates/student_templates/update_profile.html
{% extends 'base.html' %}
{% block title %}Update Profile{% endblock %}

<!DOCTYPE html>
<html lang="en">
{% block content %}

<head>
    <meta charset="UTF-8">
    <title>Update Profile</title>
    {% load static %}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
        body {
            font-family: 'Roboto', 'Open Sans', sans-serif;
        }

        .container {
            padding-top: 2rem;
        }

        .form-control,
        .btn {
            border-radius: 0.25rem;
        }

        .form-group {
            margin-bottom: 1.5rem;
            /* Increased bottom margin for better spacing */
        }

        .btn-primary {
            background-color: #0056b3;
            border-color: #0056b3;
        }

        .btn-primary:hover {
            background-color: #004b9a;
            border-color: #004b9a;
        }

        .form-select {
            border-radius: 0.25rem;
            border: 1px solid #ced4da;
        }

        .custom-checkbox {
            width: 20px;
            /* Larger width */
            height: 20px;
            /* Larger height */
            border: 2px solid #007bff;
            /* Border color */
            background-color: white;
            /* Background color */
        }
    </style>
</head>

<body>
    <div class="container mt-4">
        <div class="card">
            <div class="card-header bg-primary text-white">
                <h1>Edit Profile</h1>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <fieldset>
                        <legend>Profile Information</legend>
                        {% for field in form %}
                        <div class="form-group mb-4">
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                            {{ field }} <!-- Renders the widget as per its configuration in forms.py -->
                            {% if field.help_text %}
                            <small class="form-text text-muted">{{ field.help_text }}</small>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </fieldset>
                    <button type="submit" class="btn btn-outline-info mt-3">Update</button>
                </form>
            </div>
        </div>
        <div class="text-center mt-4">
            <a href="{% url 'student_dashboard_view' %}" class="btn btn-secondary">Back to Dashboard</a>
        </div>
    </div>
    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function () {
            var schoolSelect = document.querySelector('#id_school');
            var majorSelect = document.querySelector('#id_major');
            var initialMajorId = "{{ form.instance.major_id|default_if_none:'' }}"; // Preserving the initially selected major_id

            schoolSelect.addEventListener('change', function () {
                var schoolId = this.value;
                var url = "{% url 'ajax_get_majors_for_school' %}";

                fetch(url + '?school_id=' + schoolId)
                    .then(response => response.json())
                    .then(data => {
                        majorSelect.innerHTML = '<option value="">Select Major</option>'; // Reset major dropdown
                        data.forEach(function (major) {
                            var optionHTML = '<option value="' + major.id + '"';
                            if (major.id.toString() === initialMajorId) {
                                optionHTML += ' selected'; // Preserve selection if it matches the initial major id
                            }
                            optionHTML += '>' + major.name + '</option>';
                            majorSelect.innerHTML += optionHTML;
                        });
                    })
                    .catch(error => console.error('Error:', error));
            });

            // Trigger change event on page load if a school is already selected
            if (schoolSelect.value) {
                schoolSelect.dispatchEvent(new Event('change'));
            }
        });
    </script>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
{% endblock %}

</html>